{{- /* PostgreSQL PVC */ -}}
{{- if and .Values.postgresql.enabled .Values.postgresql.persistence.enabled (not .Values.postgresql.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "snake-game.fullname" . }}-postgresql-pvc
  labels:
    {{- include "snake-game.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
    {{- with .Values.postgresql.persistence.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.postgresql.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.postgresql.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | default "5Gi" }}
  {{- if .Values.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }}
  {{- end }}
{{- end }}

{{- /* Version-Specific PVCs */ -}}
{{- range $version := list "version1" "version2" }}
{{- if index $.Values.app $version "enabled" }}
{{- $pvcValues := index $.Values.app $version "persistence" | default dict }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "snake-game.fullname" $ }}-{{ $version }}-data
  labels:
    {{- include "snake-game.labels" $ | nindent 4 }}
    app.kubernetes.io/version: {{ $version | replace "version" "" | quote }}
    {{- with $pvcValues.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $pvcValues.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ $pvcValues.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $pvcValues.size | default "1Gi" }}
  {{- if $pvcValues.storageClass }}
  storageClassName: {{ $pvcValues.storageClass | quote }}
  {{- end }}
{{- end }}
{{- end }}
