{{- if .Values.app.version1.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "snake-game.fullname" . }}-v1
  labels:
    {{- include "snake-game.labels" . | nindent 4 }}
    app.kubernetes.io/version: "1.0"
spec:
  type: {{ .Values.app.version1.service.type }}
  ports:
    - port: {{ .Values.app.version1.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "snake-game.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/version: "1.0"
{{- end }}

{{- if .Values.app.version2.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "snake-game.fullname" . }}-v2
  labels:
    {{- include "snake-game.labels" . | nindent 4 }}
    app.kubernetes.io/version: "2.0"
spec:
  type: {{ .Values.app.version2.service.type }}
  ports:
    - port: {{ .Values.app.version2.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "snake-game.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/version: "2.0"
{{- end }}
